#!/bin/bash  
# chkconfig: - 85 15  
# description: svn server in centos6


.  /etc/init.d/functions
SVN_HOME=/usr/local/svn/sunny  

if [ ! -f "/usr/bin/svnserve" ]  
   then  
       echo "svnserver startup: cannot start"  
   exit  
fi 


case "$1" in  
     start)  
          echo "Starting svnserve..."  
          /usr/bin/svnserve -d --listen-port 3690 -r $SVN_HOME  
          echo "Finished!"  
          ;;  
     stop)  
          echo "Stoping svnserve..."  
          killall svnserve  
          echo "Finished!"  
          ;;  
     restart)  
            $0 stop  
            $0 start  
  
  
          ;;
    status)
        svnport=`netstat -natp | grep svnserve | awk -F" " '{print $4}' | awk -F: '{print $2}'`
        pid=`ps aux | grep svnserve | grep -v "grep" | awk '{print $2}'`
        if [ $svnport -eq 3690 ]
        then
                echo "SVN Server (pid:$pid) is running..."  success
        else
                echo "SVN Server was stoped..."   failure
        fi
          
          ;;
          
        *)  
          echo "Usage:svn { start | stop |restart |status } "  
          exit 1  
esac
